{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "657c2549-afab-44d2-bbe6-df6034e92d25",
   "metadata": {},
   "source": [
    "#### Download ERA5 data for the State of the Climate Report"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a8f4bacd-7f1c-43a1-85d7-0496a0e87c60",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.\n",
      "Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.\n"
     ]
    }
   ],
   "source": [
    "from functions.download_era5_cdsapi import download_era5_cdsapi\n",
    "\n",
    "import numpy as np\n",
    "import calendar"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "8c5533ab-544e-4d49-a913-4d0c9f9a913b",
   "metadata": {},
   "outputs": [],
   "source": [
    "dwn_path = '/Volumes/LaCie/Work/data/era5/2024_soc_report/'\n",
    "\n",
    "years = np.arange(1991, 1998, 1)\n",
    "months = np.arange(1, 13, 1)\n",
    "\n",
    "var = [\n",
    "    'surface_sensible_heat_flux',    \n",
    "    # '2m_dewpoint_temperature',\n",
    "    # '2m_temperature',\n",
    "    # '10m_v_component_of_wind',\n",
    "    # '10m_u_component_of_wind',\n",
    "    # 'sea_surface_temperature',\n",
    "    # 'skin_temperature',\n",
    "    # 'surface_pressure',\n",
    "    'surface_net_solar_radiation',\n",
    "    'surface_net_thermal_radiation',\n",
    "    'surface_latent_heat_flux',\n",
    "    'sea_ice_cover',\n",
    "    # 'total_precipitation',\n",
    "    # 'evaporation'\n",
    "      ]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "34a1175e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# download hourly files for 2023\n",
    "\n",
    "for v in var:\n",
    "    \n",
    "    for year in years:\n",
    "        \n",
    "        for month in months:\n",
    "            \n",
    "            # Determine the number of days in the current month\n",
    "            num_days = calendar.monthrange(year, month)[1]\n",
    "            \n",
    "            # Create a list of days using list comprehension\n",
    "            days = [f'{d:02}' for d in range(1, num_days + 1)]\n",
    "            \n",
    "            # Format month as a string with leading zero if needed\n",
    "            month_str = f'{month:02}'\n",
    "            \n",
    "            # Download Monthly Data\n",
    "            # dwn_era5.download_era5_cdsapi(var=v, days=days, month=month_str, year=str(year), dataset='reanalysis-era5-single-levels-monthly-means', product_type='monthly_averaged_reanalysis', path=dwn_path)\n",
    "            download_era5_cdsapi(var=v, days=days, month=month_str, year=str(year), dataset='reanalysis-era5-single-levels', product_type='reanalysis', path=dwn_path)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "7e8cc033-d13e-49be-82be-a89fcdadf5bb",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-02-02 17:26:46,331 INFO Welcome to the CDS\n",
      "2024-02-02 17:26:46,331 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-02 17:26:46,685 INFO Request is queued\n",
      "2024-02-02 19:03:46,170 INFO Request is completed\n",
      "2024-02-02 19:03:46,175 INFO Downloading https://download-0011-clone.copernicus-climate.eu/cache-compute-0011/cache/data3/adaptor.mars.internal-1706893411.7325404-31860-14-55786628-0144-4403-84c7-9b76802008a5.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199101.nc (23.8M)\n",
      "2024-02-02 19:04:27,772 INFO Download rate 586K/s   \n",
      "2024-02-02 19:04:28,251 INFO Welcome to the CDS\n",
      "2024-02-02 19:04:28,254 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-02 19:04:28,563 INFO Request is queued\n",
      "2024-02-02 20:49:17,483 WARNING Connection error: [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))]. Attempt 1 of 500.\n",
      "2024-02-02 20:49:17,485 WARNING Retrying in 120 seconds\n",
      "2024-02-02 21:06:17,790 INFO Retrying now...\n",
      "2024-02-02 21:06:18,613 INFO Request is completed\n",
      "2024-02-02 21:06:18,616 INFO Downloading https://download-0007-clone.copernicus-climate.eu/cache-compute-0007/cache/data5/adaptor.mars.internal-1706899372.7287474-27793-18-273866ab-7d88-4f89-ad88-eb9244e283b4.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199102.nc (23.8M)\n",
      "2024-02-02 21:07:01,382 INFO Download rate 570K/s    \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Read timed out. (read timeout=60)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-02-02 21:24:56,694 INFO Welcome to the CDS\n",
      "2024-02-02 21:24:56,696 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-02 21:24:56,998 INFO Request is queued\n",
      "2024-02-02 21:31:29,586 WARNING Connection error: [HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Read timed out. (read timeout=60)]. Attempt 1 of 500.\n",
      "2024-02-02 21:31:29,589 WARNING Retrying in 120 seconds\n",
      "2024-02-02 21:33:29,595 INFO Retrying now...\n",
      "2024-02-02 22:51:32,787 INFO Request is completed\n",
      "2024-02-02 22:51:32,795 INFO Downloading https://download-0002-clone.copernicus-climate.eu/cache-compute-0002/cache/data4/adaptor.mars.internal-1706907057.5141373-25979-4-8e8f583a-cc12-45ed-917b-ca6444752259.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199103.nc (23.8M)\n",
      "2024-02-02 22:52:17,961 INFO Download rate 539.7K/s \n",
      "2024-02-02 22:52:18,179 INFO Welcome to the CDS\n",
      "2024-02-02 22:52:18,184 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-02 22:52:18,468 INFO Request is queued\n",
      "2024-02-03 00:13:12,267 INFO Request is completed\n",
      "2024-02-03 00:13:12,272 INFO Downloading https://download-0011-clone.copernicus-climate.eu/cache-compute-0011/cache/data3/adaptor.mars.internal-1706911944.4467404-22761-8-c4d5f267-a8ab-4ca7-98ea-3f0398544ebf.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199104.nc (23.8M)\n",
      "2024-02-03 00:14:01,528 INFO Download rate 494.9K/s \n",
      "2024-02-03 00:14:02,077 INFO Welcome to the CDS\n",
      "2024-02-03 00:14:02,080 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-03 00:14:02,336 INFO Request is queued\n",
      "2024-02-03 01:51:40,797 INFO Request is completed\n",
      "2024-02-03 01:51:40,801 INFO Downloading https://download-0021.copernicus-climate.eu/cache-compute-0021/cache/data4/adaptor.mars.internal-1706916753.2725434-10793-14-2f18f2dd-74e9-4077-a79a-b24c9761d516.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199105.nc (23.8M)\n",
      "2024-02-03 01:52:22,608 INFO Download rate 583.1K/s \n",
      "2024-02-03 01:52:23,039 INFO Welcome to the CDS\n",
      "2024-02-03 01:52:23,042 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-03 01:52:23,367 INFO Request is queued\n",
      "2024-02-03 02:26:45,839 WARNING Connection error: [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))]. Attempt 1 of 500.\n",
      "2024-02-03 02:26:45,842 WARNING Retrying in 120 seconds\n",
      "2024-02-03 02:28:45,856 INFO Retrying now...\n",
      "2024-02-03 02:31:26,375 WARNING Connection error: [HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Read timed out. (read timeout=60)]. Attempt 1 of 500.\n",
      "2024-02-03 02:31:26,379 WARNING Retrying in 120 seconds\n",
      "2024-02-03 02:33:45,946 INFO Retrying now...\n",
      "2024-02-03 02:45:32,163 WARNING Connection error: [HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Read timed out. (read timeout=60)]. Attempt 1 of 500.\n",
      "2024-02-03 02:45:32,167 WARNING Retrying in 120 seconds\n",
      "2024-02-03 03:02:32,378 INFO Retrying now...\n",
      "2024-02-03 03:02:33,216 INFO Request is completed\n",
      "2024-02-03 03:02:33,219 INFO Downloading https://download-0016.copernicus-climate.eu/cache-compute-0016/cache/data8/adaptor.mars.internal-1706921985.3626382-27693-4-3e4a28da-ab60-4a9f-b251-e8fbe5adcd1f.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199106.nc (23.8M)\n",
      "2024-02-03 03:20:15,795 ERROR Download interupted: HTTPSConnectionPool(host='download-0016.copernicus-climate.eu', port=443): Read timed out.\n",
      "2024-02-03 03:20:15,797 ERROR Download incomplete, downloaded 18968576 byte(s) out of 24960768\n",
      "2024-02-03 03:20:15,799 WARNING Sleeping 10 seconds\n",
      "2024-02-03 03:20:25,812 WARNING Resuming download at byte 18968576\n",
      "2024-02-03 03:20:35,092 INFO Download rate 22.5K/s \n",
      "2024-02-03 03:21:35,116 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-03 03:21:36,053 INFO Request is queued\n",
      "2024-02-03 03:25:13,933 WARNING Connection error: [HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Read timed out. (read timeout=60)]. Attempt 1 of 500.\n",
      "2024-02-03 03:25:13,937 WARNING Retrying in 120 seconds\n",
      "2024-02-03 03:45:24,414 INFO Retrying now...\n",
      "2024-02-03 04:02:34,069 WARNING Connection error: [HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Read timed out. (read timeout=60)]. Attempt 1 of 500.\n",
      "2024-02-03 04:02:34,072 WARNING Retrying in 120 seconds\n",
      "2024-02-03 04:20:48,189 INFO Retrying now...\n",
      "2024-02-03 04:31:29,301 WARNING Connection error: [HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Read timed out. (read timeout=60)]. Attempt 1 of 500.\n",
      "2024-02-03 04:31:29,303 WARNING Retrying in 120 seconds\n",
      "2024-02-03 04:50:47,537 INFO Retrying now...\n",
      "2024-02-03 05:06:47,895 WARNING Connection error: [HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Read timed out. (read timeout=60)]. Attempt 2 of 500.\n",
      "2024-02-03 05:06:47,898 WARNING Retrying in 120 seconds\n",
      "2024-02-03 05:08:47,934 INFO Retrying now...\n",
      "2024-02-03 05:08:48,759 INFO Request is completed\n",
      "2024-02-03 05:08:48,762 INFO Downloading https://download-0009-clone.copernicus-climate.eu/cache-compute-0009/cache/data8/adaptor.mars.internal-1706926957.5066547-3527-4-c743a036-7ff2-4cc1-861c-c59ac6cd2e83.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199107.nc (23.8M)\n",
      "2024-02-03 05:26:46,178 ERROR Download interupted: HTTPSConnectionPool(host='download-0009-clone.copernicus-climate.eu', port=443): Read timed out.\n",
      "2024-02-03 05:26:46,180 ERROR Download incomplete, downloaded 3464192 byte(s) out of 24960768\n",
      "2024-02-03 05:26:46,183 WARNING Sleeping 10 seconds\n",
      "2024-02-03 05:26:56,195 WARNING Resuming download at byte 3464192\n",
      "2024-02-03 05:43:44,034 ERROR Download interupted: HTTPSConnectionPool(host='download-0009-clone.copernicus-climate.eu', port=443): Read timed out.\n",
      "2024-02-03 05:43:44,035 ERROR Download incomplete, downloaded 15367168 byte(s) out of 24960768\n",
      "2024-02-03 05:43:44,035 WARNING Sleeping 15.0 seconds\n",
      "2024-02-03 05:43:59,050 WARNING Resuming download at byte 15367168\n",
      "2024-02-03 05:44:14,909 INFO Download rate 11.5K/s  \n",
      "2024-02-03 05:45:15,147 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-03 05:45:16,237 INFO Request is queued\n",
      "2024-02-03 06:18:40,120 WARNING Connection error: [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))]. Attempt 1 of 500.\n",
      "2024-02-03 06:18:40,121 WARNING Retrying in 120 seconds\n",
      "2024-02-03 06:35:39,250 INFO Retrying now...\n",
      "2024-02-03 06:49:25,582 WARNING Connection error: [HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Read timed out. (read timeout=60)]. Attempt 1 of 500.\n",
      "2024-02-03 06:49:25,585 WARNING Retrying in 120 seconds\n",
      "2024-02-03 06:51:25,603 INFO Retrying now...\n",
      "2024-02-03 06:51:26,420 INFO Request is completed\n",
      "2024-02-03 06:51:26,423 INFO Downloading https://download-0019.copernicus-climate.eu/cache-compute-0019/cache/data4/adaptor.mars.internal-1706935667.8710046-17576-14-c2167f93-7f5f-452a-a5a7-40d720c5ea21.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199108.nc (23.8M)\n",
      "2024-02-03 06:52:13,128 INFO Download rate 521.9K/s \n",
      "2024-02-03 06:52:13,630 INFO Welcome to the CDS\n",
      "2024-02-03 06:52:13,631 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-03 06:52:13,932 INFO Request is queued\n",
      "2024-02-03 07:50:57,286 INFO Request is completed\n",
      "2024-02-03 07:50:57,291 INFO Downloading https://download-0008-clone.copernicus-climate.eu/cache-compute-0008/cache/data0/adaptor.mars.internal-1706939395.8456504-5981-16-2b4bcea0-0fbe-45e0-bdc1-109dcb8fd26d.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199109.nc (23.8M)\n",
      "2024-02-03 07:51:40,474 INFO Download rate 564.5K/s  \n",
      "2024-02-03 07:51:40,895 INFO Welcome to the CDS\n",
      "2024-02-03 07:51:40,899 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-03 07:51:41,240 INFO Request is queued\n",
      "2024-02-03 08:48:23,562 INFO Request is completed\n",
      "2024-02-03 08:48:23,564 INFO Downloading https://download-0016.copernicus-climate.eu/cache-compute-0016/cache/data5/adaptor.mars.internal-1706942830.3020232-5036-15-408ba69a-7600-42ab-8e16-5d355bfc334f.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199110.nc (23.8M)\n",
      "2024-02-03 08:49:10,571 INFO Download rate 518.6K/s  \n",
      "2024-02-03 08:49:10,987 INFO Welcome to the CDS\n",
      "2024-02-03 08:49:10,990 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-03 08:49:11,298 INFO Request is queued\n",
      "2024-02-03 09:35:49,846 INFO Request is completed\n",
      "2024-02-03 09:35:49,848 INFO Downloading https://download-0010-clone.copernicus-climate.eu/cache-compute-0010/cache/data0/adaptor.mars.internal-1706945673.2066994-9279-1-757dcc8b-8c92-41fd-a1c5-afc2be616c78.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199111.nc (23.8M)\n",
      "2024-02-03 09:36:47,380 INFO Download rate 423.7K/s  \n",
      "2024-02-03 09:36:47,778 INFO Welcome to the CDS\n",
      "2024-02-03 09:36:47,779 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-03 09:36:48,087 INFO Request is queued\n",
      "2024-02-03 10:15:57,420 WARNING Connection error: [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))]. Attempt 1 of 500.\n",
      "2024-02-03 10:15:57,422 WARNING Retrying in 120 seconds\n",
      "2024-02-03 10:17:57,434 INFO Retrying now...\n",
      "2024-02-03 10:21:59,844 INFO Request is completed\n",
      "2024-02-03 10:21:59,847 INFO Downloading https://download-0016.copernicus-climate.eu/cache-compute-0016/cache/data4/adaptor.mars.internal-1706948474.3508697-29240-11-28a372fa-f452-41f3-a6ff-f7eed3bef89d.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199112.nc (23.8M)\n",
      "2024-02-03 10:22:55,594 INFO Download rate 437.3K/s  \n",
      "2024-02-03 10:22:55,793 INFO Welcome to the CDS\n",
      "2024-02-03 10:22:55,795 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-03 10:22:56,059 INFO Request is queued\n",
      "2024-02-03 11:05:32,893 INFO Request is completed\n",
      "2024-02-03 11:05:32,905 INFO Downloading https://download-0012-clone.copernicus-climate.eu/cache-compute-0012/cache/data7/adaptor.mars.internal-1706951100.5835748-13058-1-5be9cc8d-0201-40ce-b621-0f2330600819.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199201.nc (23.8M)\n",
      "2024-02-03 11:06:23,720 INFO Download rate 479.8K/s  \n",
      "2024-02-03 11:06:24,135 INFO Welcome to the CDS\n",
      "2024-02-03 11:06:24,138 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-03 11:06:24,391 INFO Request is queued\n",
      "2024-02-03 11:51:02,363 INFO Request is completed\n",
      "2024-02-03 11:51:02,371 INFO Downloading https://download-0014-clone.copernicus-climate.eu/cache-compute-0014/cache/data8/adaptor.mars.internal-1706953828.216699-9948-4-c58f214c-6aff-45c5-9aae-6a32bde7452f.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199202.nc (23.8M)\n",
      "2024-02-03 11:51:47,472 INFO Download rate 540.5K/s  \n",
      "2024-02-03 11:51:47,884 INFO Welcome to the CDS\n",
      "2024-02-03 11:51:47,887 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels-monthly-means\n",
      "2024-02-03 11:51:48,171 INFO Request is queued\n",
      "2024-02-03 15:00:12,976 WARNING Connection error: [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))]. Attempt 1 of 500.\n",
      "2024-02-03 15:00:12,982 WARNING Retrying in 120 seconds\n",
      "2024-02-03 17:01:01,374 INFO Retrying now...\n",
      "2024-02-03 17:01:02,232 INFO Request is completed\n",
      "2024-02-03 17:01:02,235 INFO Downloading https://download-0001-clone.copernicus-climate.eu/cache-compute-0001/cache/data8/adaptor.mars.internal-1706956512.0807774-21898-17-e0296e8d-16fe-41cb-8857-78988e0f46cc.nc to /Volumes/LaCie/Work/data/era5/2024_soc_report/surface_sensible_heat_flux_199203.nc (23.8M)\n",
      "2024-02-03 17:31:59,746 WARNING Connection error: [HTTPSConnectionPool(host='download-0001-clone.copernicus-climate.eu', port=443): Read timed out. (read timeout=60)]. Attempt 1 of 500.\n",
      "2024-02-03 17:31:59,748 WARNING Retrying in 120 seconds\n",
      "2024-02-03 19:15:16,638 INFO Retrying now...\n",
      "2024-02-03 19:17:04,361 WARNING Connection error: [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))]. Attempt 2 of 500.\n",
      "2024-02-03 19:17:04,363 WARNING Retrying in 120 seconds\n",
      "2024-02-03 20:17:35,974 INFO Retrying now...\n",
      "2024-02-03 21:34:05,530 ERROR Download interupted: HTTPSConnectionPool(host='download-0001-clone.copernicus-climate.eu', port=443): Read timed out.\n",
      "IOStream.flush timed out\n",
      "2024-02-03 21:34:07,081 ERROR Download incomplete, downloaded 7404544 byte(s) out of 24960768\n",
      "2024-02-03 21:34:07,082 WARNING Sleeping 10 seconds\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-02-03 21:41:11,507 WARNING Resuming download at byte 7404544\n",
      "2024-02-03 21:41:11,522 WARNING Connection error: [HTTPSConnectionPool(host='download-0001-clone.copernicus-climate.eu', port=443): Max retries exceeded with url: /cache-compute-0001/cache/data8/adaptor.mars.internal-1706956512.0807774-21898-17-e0296e8d-16fe-41cb-8857-78988e0f46cc.nc (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x115a03170>: Failed to resolve 'download-0001-clone.copernicus-climate.eu' ([Errno 8] nodename nor servname provided, or not known)\"))]. Attempt 1 of 500.\n",
      "2024-02-03 21:41:11,523 WARNING Retrying in 120 seconds\n",
      "2024-02-03 21:47:32,432 INFO Retrying now...\n",
      "2024-02-03 22:05:58,792 ERROR Download interupted: HTTPSConnectionPool(host='download-0001-clone.copernicus-climate.eu', port=443): Read timed out.\n",
      "2024-02-03 22:05:58,793 ERROR Download incomplete, downloaded 7464960 byte(s) out of 24960768\n",
      "2024-02-03 22:05:58,793 WARNING Sleeping 15.0 seconds\n",
      "2024-02-03 22:19:33,246 WARNING Resuming download at byte 7464960\n",
      "                                                    \r"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Read timed out. (read timeout=60)\n"
     ]
    },
    {
     "ename": "ChunkedEncodingError",
     "evalue": "('Connection broken: IncompleteRead(6300170 bytes read, 11195638 more expected)', IncompleteRead(6300170 bytes read, 11195638 more expected))",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIncompleteRead\u001b[0m                            Traceback (most recent call last)",
      "File \u001b[0;32m~/opt/anaconda3/envs/soc_env/lib/python3.12/site-packages/urllib3/response.py:712\u001b[0m, in \u001b[0;36mHTTPResponse._error_catcher\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    711\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 712\u001b[0m     \u001b[38;5;28;01myield\u001b[39;00m\n\u001b[1;32m    714\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m SocketTimeout \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m    715\u001b[0m     \u001b[38;5;66;03m# FIXME: Ideally we'd like to include the url in the ReadTimeoutError but\u001b[39;00m\n\u001b[1;32m    716\u001b[0m     \u001b[38;5;66;03m# there is yet no clean way to get at it from this context.\u001b[39;00m\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/soc_env/lib/python3.12/site-packages/urllib3/response.py:833\u001b[0m, in \u001b[0;36mHTTPResponse._raw_read\u001b[0;34m(self, amt)\u001b[0m\n\u001b[1;32m    823\u001b[0m         \u001b[38;5;28;01mif\u001b[39;00m (\n\u001b[1;32m    824\u001b[0m             \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39menforce_content_length\n\u001b[1;32m    825\u001b[0m             \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mlength_remaining \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    831\u001b[0m             \u001b[38;5;66;03m# raised during streaming, so all calls with incorrect\u001b[39;00m\n\u001b[1;32m    832\u001b[0m             \u001b[38;5;66;03m# Content-Length are caught.\u001b[39;00m\n\u001b[0;32m--> 833\u001b[0m             \u001b[38;5;28;01mraise\u001b[39;00m IncompleteRead(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_fp_bytes_read, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mlength_remaining)\n\u001b[1;32m    835\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m data:\n",
      "\u001b[0;31mIncompleteRead\u001b[0m: IncompleteRead(6300170 bytes read, 11195638 more expected)",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mProtocolError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[0;32m~/opt/anaconda3/envs/soc_env/lib/python3.12/site-packages/requests/models.py:816\u001b[0m, in \u001b[0;36mResponse.iter_content.<locals>.generate\u001b[0;34m()\u001b[0m\n\u001b[1;32m    815\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 816\u001b[0m     \u001b[38;5;28;01myield from\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mraw\u001b[38;5;241m.\u001b[39mstream(chunk_size, decode_content\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m)\n\u001b[1;32m    817\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m ProtocolError \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/soc_env/lib/python3.12/site-packages/urllib3/response.py:934\u001b[0m, in \u001b[0;36mHTTPResponse.stream\u001b[0;34m(self, amt, decode_content)\u001b[0m\n\u001b[1;32m    933\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m is_fp_closed(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_fp) \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_decoded_buffer) \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[0;32m--> 934\u001b[0m     data \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mread\u001b[49m\u001b[43m(\u001b[49m\u001b[43mamt\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mamt\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdecode_content\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mdecode_content\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    936\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m data:\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/soc_env/lib/python3.12/site-packages/urllib3/response.py:905\u001b[0m, in \u001b[0;36mHTTPResponse.read\u001b[0;34m(self, amt, decode_content, cache_content)\u001b[0m\n\u001b[1;32m    901\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_decoded_buffer) \u001b[38;5;241m<\u001b[39m amt \u001b[38;5;129;01mand\u001b[39;00m data:\n\u001b[1;32m    902\u001b[0m     \u001b[38;5;66;03m# TODO make sure to initially read enough data to get past the headers\u001b[39;00m\n\u001b[1;32m    903\u001b[0m     \u001b[38;5;66;03m# For example, the GZ file header takes 10 bytes, we don't want to read\u001b[39;00m\n\u001b[1;32m    904\u001b[0m     \u001b[38;5;66;03m# it one byte at a time\u001b[39;00m\n\u001b[0;32m--> 905\u001b[0m     data \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_raw_read\u001b[49m\u001b[43m(\u001b[49m\u001b[43mamt\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    906\u001b[0m     decoded_data \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_decode(data, decode_content, flush_decoder)\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/soc_env/lib/python3.12/site-packages/urllib3/response.py:811\u001b[0m, in \u001b[0;36mHTTPResponse._raw_read\u001b[0;34m(self, amt)\u001b[0m\n\u001b[1;32m    809\u001b[0m fp_closed \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mgetattr\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_fp, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mclosed\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28;01mFalse\u001b[39;00m)\n\u001b[0;32m--> 811\u001b[0m \u001b[43m\u001b[49m\u001b[38;5;28;43;01mwith\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_error_catcher\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m:\u001b[49m\n\u001b[1;32m    812\u001b[0m \u001b[43m    \u001b[49m\u001b[43mdata\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_fp_read\u001b[49m\u001b[43m(\u001b[49m\u001b[43mamt\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mif\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mnot\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mfp_closed\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01melse\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;124;43mb\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/soc_env/lib/python3.12/contextlib.py:158\u001b[0m, in \u001b[0;36m_GeneratorContextManager.__exit__\u001b[0;34m(self, typ, value, traceback)\u001b[0m\n\u001b[1;32m    157\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 158\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgen\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mthrow\u001b[49m\u001b[43m(\u001b[49m\u001b[43mvalue\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    159\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[1;32m    160\u001b[0m     \u001b[38;5;66;03m# Suppress StopIteration *unless* it's the same exception that\u001b[39;00m\n\u001b[1;32m    161\u001b[0m     \u001b[38;5;66;03m# was passed to throw().  This prevents a StopIteration\u001b[39;00m\n\u001b[1;32m    162\u001b[0m     \u001b[38;5;66;03m# raised inside the \"with\" statement from being suppressed.\u001b[39;00m\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/soc_env/lib/python3.12/site-packages/urllib3/response.py:729\u001b[0m, in \u001b[0;36mHTTPResponse._error_catcher\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    727\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m (HTTPException, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m    728\u001b[0m     \u001b[38;5;66;03m# This includes IncompleteRead.\u001b[39;00m\n\u001b[0;32m--> 729\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m ProtocolError(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mConnection broken: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00me\u001b[38;5;132;01m!r}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m, e) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01me\u001b[39;00m\n\u001b[1;32m    731\u001b[0m \u001b[38;5;66;03m# If no exception is thrown, we should avoid cleaning up\u001b[39;00m\n\u001b[1;32m    732\u001b[0m \u001b[38;5;66;03m# unnecessarily.\u001b[39;00m\n",
      "\u001b[0;31mProtocolError\u001b[0m: ('Connection broken: IncompleteRead(6300170 bytes read, 11195638 more expected)', IncompleteRead(6300170 bytes read, 11195638 more expected))",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mChunkedEncodingError\u001b[0m                      Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 20\u001b[0m\n\u001b[1;32m     16\u001b[0m month_str \u001b[38;5;241m=\u001b[39m \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mmonth\u001b[38;5;132;01m:\u001b[39;00m\u001b[38;5;124m02\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m     18\u001b[0m \u001b[38;5;66;03m# Download Monthly Data\u001b[39;00m\n\u001b[1;32m     19\u001b[0m \u001b[38;5;66;03m# dwn_era5.download_era5_cdsapi(var=v, days=days, month=month_str, year=str(year), dataset='reanalysis-era5-single-levels-monthly-means', product_type='monthly_averaged_reanalysis', path=dwn_path)\u001b[39;00m\n\u001b[0;32m---> 20\u001b[0m \u001b[43mdownload_era5_cdsapi\u001b[49m\u001b[43m(\u001b[49m\u001b[43mvar\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mv\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdays\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mdays\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmonth\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmonth_str\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43myear\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mstr\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43myear\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdataset\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mreanalysis-era5-single-levels-monthly-means\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mproduct_type\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mreanalysis\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mpath\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mdwn_path\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Library/CloudStorage/GoogleDrive-marceldpl10@gmail.com/My Drive/projects/2024_soc_heat_flux/soc-heat-fluxes-2024/code/functions/download_era5_cdsapi.py:47\u001b[0m, in \u001b[0;36mdownload_era5_cdsapi\u001b[0;34m(var, days, month, year, dataset, product_type, path)\u001b[0m\n\u001b[1;32m     27\u001b[0m     params \u001b[38;5;241m=\u001b[39m {\n\u001b[1;32m     28\u001b[0m               \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mvariable\u001b[39m\u001b[38;5;124m'\u001b[39m: [var],\n\u001b[1;32m     29\u001b[0m               \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mproduct_type\u001b[39m\u001b[38;5;124m'\u001b[39m: product_type,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     42\u001b[0m               \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mformat\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mnetcdf\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m     43\u001b[0m              }\n\u001b[1;32m     45\u001b[0m fl \u001b[38;5;241m=\u001b[39m cds\u001b[38;5;241m.\u001b[39mretrieve(dataset, params) \u001b[38;5;66;03m# download the file \u001b[39;00m\n\u001b[0;32m---> 47\u001b[0m \u001b[43mfl\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdownload\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpath\u001b[49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[38;5;28;43mstr\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mvar\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m_\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[38;5;28;43mstr\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43myear\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[38;5;28;43mstr\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mmonth\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m.nc\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m \u001b[38;5;66;03m# load into memory\u001b[39;00m\n\u001b[1;32m     49\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/soc_env/lib/python3.12/site-packages/cdsapi/api.py:171\u001b[0m, in \u001b[0;36mResult.download\u001b[0;34m(self, target)\u001b[0m\n\u001b[1;32m    170\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mdownload\u001b[39m(\u001b[38;5;28mself\u001b[39m, target\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m):\n\u001b[0;32m--> 171\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_download\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mlocation\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcontent_length\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtarget\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/soc_env/lib/python3.12/site-packages/cdsapi/api.py:131\u001b[0m, in \u001b[0;36mResult._download\u001b[0;34m(self, url, size, target)\u001b[0m\n\u001b[1;32m    129\u001b[0m pbar\u001b[38;5;241m.\u001b[39mupdate(total)\n\u001b[1;32m    130\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mopen\u001b[39m(target, mode) \u001b[38;5;28;01mas\u001b[39;00m f:\n\u001b[0;32m--> 131\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43;01mfor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mchunk\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01min\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mr\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43miter_content\u001b[49m\u001b[43m(\u001b[49m\u001b[43mchunk_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m1024\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m:\u001b[49m\n\u001b[1;32m    132\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;28;43;01mif\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mchunk\u001b[49m\u001b[43m:\u001b[49m\n\u001b[1;32m    133\u001b[0m \u001b[43m            \u001b[49m\u001b[43mf\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwrite\u001b[49m\u001b[43m(\u001b[49m\u001b[43mchunk\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/soc_env/lib/python3.12/site-packages/requests/models.py:818\u001b[0m, in \u001b[0;36mResponse.iter_content.<locals>.generate\u001b[0;34m()\u001b[0m\n\u001b[1;32m    816\u001b[0m     \u001b[38;5;28;01myield from\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mraw\u001b[38;5;241m.\u001b[39mstream(chunk_size, decode_content\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m)\n\u001b[1;32m    817\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m ProtocolError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m--> 818\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m ChunkedEncodingError(e)\n\u001b[1;32m    819\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m DecodeError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m    820\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m ContentDecodingError(e)\n",
      "\u001b[0;31mChunkedEncodingError\u001b[0m: ('Connection broken: IncompleteRead(6300170 bytes read, 11195638 more expected)', IncompleteRead(6300170 bytes read, 11195638 more expected))"
     ]
    }
   ],
   "source": [
    "# download monthly files\n",
    "\n",
    "for v in var:\n",
    "    \n",
    "    for year in years:\n",
    "        \n",
    "        for month in months:\n",
    "            \n",
    "            # Determine the number of days in the current month\n",
    "            num_days = calendar.monthrange(year, month)[1]\n",
    "            \n",
    "            # Create a list of days using list comprehension\n",
    "            days = [f'{d:02}' for d in range(1, num_days + 1)]\n",
    "            \n",
    "            # Format month as a string with leading zero if needed\n",
    "            month_str = f'{month:02}'\n",
    "            \n",
    "            # Download Monthly Data\n",
    "            # dwn_era5.download_era5_cdsapi(var=v, days=days, month=month_str, year=str(year), dataset='reanalysis-era5-single-levels-monthly-means', product_type='monthly_averaged_reanalysis', path=dwn_path)\n",
    "            download_era5_cdsapi(var=v, days=days, month=month_str, year=str(year), dataset='reanalysis-era5-single-levels-monthly-means', product_type='reanalysis', path=dwn_path)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dd1553a8-4890-404e-b11d-4a2760245ea6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
